### ISSUE TITLE
mobile queries

### ISSUE THREAD

**Issue by jaeming** [webkea/website#10]
need to adjust some text sizes for mobile.

**Comment by ennynz** [comment]
mobile menu needs to be fixed for small phones as well.

**Comment by jaeming** [comment]
Mobile Menu fixed! That was a bitch.

**Comment by jaeming** [comment]
https://github.com/webkea/website/commit/58419f37f6fb8d7fcddd131713cc0f2a34b6e5fd
The above commit fixes a lot of the font-size and spacing... There is still work to be done in the portfolio and footer though. Also, a 2nd look at white space maybe...?

**Comment by jaeming** [comment]
https://github.com/webkea/website/commit/df9787f6ef805960fb963b14d118014f1a103148
Fixed in the above commit.
