### ISSUE TITLE
forms

### ISSUE THREAD

**Issue by ennynz** [webkea/website#2]
make top email form and footer email form functional.

**Comment by ennynz** [comment]
first we need the email address and we'll use that with simple form.

**Comment by ennynz** [comment]
email address opened info@webkea.co.nz

**Comment by jaeming** [comment]
The forms are done. I've also included a js function with a notification when a form has been sent.  You won't see it until we've deployed though as the redirect sends to the actual web address, which is still "coming soon". Tested it and the emails are coming through on the gmail account.
